# Generated by Django 4.2.2 on 2023-06-26 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SetorVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ControleVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_entrada', models.DateTimeField()),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('placa_carro', models.CharField(blank=True, max_length=7, null=True)),
                ('empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('nota_fiscal', models.CharField(blank=True, max_length=10, null=True)),
                ('registro_saida', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('autorizacao', models.CharField(blank=True, max_length=50, null=True)),
                ('porteiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControleVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('registro_entrada', models.DateField()),
                ('registro_saida', models.DateTimeField(blank=True, null=True)),
                ('porteiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setorveiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ControleChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_entrega', models.DateTimeField()),
                ('registro_recebimento', models.DateTimeField(blank=True, null=True)),
                ('funcionario', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=10)),
                ('porteiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setorchave')),
            ],
        ),
    ]
